package com.kidor.vigik.data.midjourney

import com.kidor.vigik.data.midjourney.model.GetGeneratedImagesResponse
import retrofit2.http.GET
import retrofit2.http.Query

/**
 * Base URL for the MidJourney API remote server.
 */
const val MID_JOURNEY_API_BASE_URL: String = "https://mj.akgns.com/"

/**
 * MidJourney HTTP API used by Retrofit.
 */
fun interface MidJourneyApi {

    /**
     * Returns a list of random images generated by MidJourney.
     */
    @GET("images")
    suspend fun getRandomGeneratedImages(@Query("page") page: Int): GetGeneratedImagesResponse
}
